imports:
  Merchant: Domain.Types.Merchant
  MerchantOperatingCity: Domain.Types.MerchantOperatingCity
  BecknConfig: Domain.Types.BecknConfig

VehicleConfig:
  tableName: beckn_vehicle_config

  fields:
    id: Id VehicleConfig
    becknConfigId: Id BecknConfig
    category: Text
    blackListedSubscribers: "[Text]"
    buyerFinderFee: Text

  queries:
    findAllByBecknConfigId:
      kvFunction: findAllWithKV
      where: becknConfigId