name: Build Generation

on:
  workflow_dispatch:
    inputs:

      variant:
        description: 'Build Variant'
        required: true
        default: 'NyUserProdDebug'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:

      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update local.properties 
        env:
          MOBILITY_SERVICES: ${{ secrets.MOBILITY_SERVICES }}
        run: bash android-native/update_properties.sh ${{ github.event.inputs.baseUrlUser }} ${{ github.event.inputs.baseUrlDriver }} ${{ github.event.inputs.mapKey }} ${{ github.event.inputs.merchantIdUser }} ${{ github.event.inputs.merchantIdDriver }} "$MOBILITY_SERVICES"
      

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      - name: Build APK
        run: |
          cd android-native  # Adjust the path as needed
          bash github_apk_build.sh ${{ github.event.inputs.variant }}
          bash apk_path.sh ${{ github.event.inputs.variant }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.variant }}
          path: path.txt