name: Build-FE-Driver

on:
  pull_request:
    paths:
      - 'Frontend/ui-driver/**'
      - 'Frontend/ui-common/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend/ui-driver

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      - name: Install dependencies
        run: npm install && npm install purescript

      - name: Build code
        run: npm run compile:purs
