name: Build-FE

on:
  push:
    paths:
      - 'Frontend/ui-customer/**'
  pull_request:
    paths:
      - 'Frontend/ui-customer/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build code
        run: npm run build

      - name: Check if code compiles
        run: npm run check