name: Compress Lottie Files
on:
  push:
  #   paths:
  #     - 'raw/**/*.json'  # Trigger on changes to raw/*.json files

jobs:
  compress-lottie:
    name: Compress Lottie JSON Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Ensure jq is installed
      - name: Install jq
        run: sudo apt-get install jq

      # Compress Lottie JSON files directly in YAML using shell commands
      - name: Compress Lottie JSON Files
        run: |
          find . -path './raw/*.json' | while read -r json_file; do
            jq -c . "$json_file" > tmp.json && mv tmp.json "$json_file"
            echo "Compressed: $json_file"
          done

      # Commit and push the compressed files if there are any changes
      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add raw/**/*.json
          git commit -m "[github-bot] Compressed Lottie JSON files" || echo "No changes to commit"
          git push
