name: ARM64 Build and Push
on:
  push:
    branches: ["main", "prodHotPush-Common"]
  pull_request:
    branches: ["main", "prodHotPush-Common"]
  workflow_dispatch:
permissions:
  packages: write
  contents: read
  id-token: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  arm64-build:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.value }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set image name
        id: image-name
        run: |
          echo "value=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Start CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: nammayatri-arm64-build
          env-vars-for-codebuild: |
            GH_PAT=${{ secrets.GH_PAT }},
            GITHUB_ACTOR=${{ github.actor }},
            IMAGE_NAME=${{ steps.image-name.outputs.value }}
  verify-push:
    needs: arm64-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check image existence
        run: |
          docker pull ${{ needs.arm64-build.outputs.image-name }}