name: Lint and Format Code

on:
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend/

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Commit changes
        run: |
          bash format.sh
          git config --global user.name 'namma-bot'
          git config --global user.email ${{ secrets.NAMMA_BOT_EMAIL }}
          git add .
          git commit -m "frontend/refactor: [Automated] linting and formatting" || echo "No changes to commit"

      - name: Push changes
        run: |
          git remote set-url origin https://${{ secrets.BOT_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:automated-code-formatting

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: Automated linting and formatting
          title: '[Automated] Code Formatting'
          body: 'This is an auto-generated PR with code formatting changes'
          branch: automated-code-formatting
          delete-branch: true
          base: main
